/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ArtworkFileArray model module.
 * @module model/ArtworkFileArray
 * @version 0.0.1
 */
export default class ArtworkFileArray {
  /**
   * Constructs a new <code>ArtworkFileArray</code>.
   * @alias module:model/ArtworkFileArray
   * @class
   * @param artworkFile {Object} 
   */
  constructor(artworkFile) {
    this.artworkFile = artworkFile;
  }

  /**
   * Constructs a <code>ArtworkFileArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArtworkFileArray} obj Optional instance to populate.
   * @return {module:model/ArtworkFileArray} The populated <code>ArtworkFileArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArtworkFileArray();
      if (data.hasOwnProperty('ArtworkFile'))
        obj.artworkFile = ApiClient.convertToType(data['ArtworkFile'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} artworkFile
 */
ArtworkFileArray.prototype.artworkFile = undefined;

