/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import PO from './PO';

/**
 * The BodySendPo model module.
 * @module model/BodySendPo
 * @version 0.0.1
 */
export default class BodySendPo {
  /**
   * Constructs a new <code>BodySendPo</code>.
   * @alias module:model/BodySendPo
   * @class
   * @param po {module:model/PO} 
   */
  constructor(po) {
    this.po = po;
  }

  /**
   * Constructs a <code>BodySendPo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BodySendPo} obj Optional instance to populate.
   * @return {module:model/BodySendPo} The populated <code>BodySendPo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BodySendPo();
      if (data.hasOwnProperty('po'))
        obj.po = PO.constructFromObject(data['po']);
      if (data.hasOwnProperty('pub_api_key'))
        obj.pubApiKey = ApiClient.convertToType(data['pub_api_key'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/PO} po
 */
BodySendPo.prototype.po = undefined;

/**
 * @member {Object} pubApiKey
 */
BodySendPo.prototype.pubApiKey = undefined;

