/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ChargePrice model module.
 * @module model/ChargePrice
 * @version 0.0.1
 */
export default class ChargePrice {
  /**
   * Constructs a new <code>ChargePrice</code>.
   * @alias module:model/ChargePrice
   * @class
   * @param xMinQty {Object} 
   * @param xUom {Object} 
   * @param yMinQty {Object} 
   * @param yUom {Object} 
   * @param price {Object} 
   * @param discountCode {Object} The industry discount code associated with the price
   * @param repeatPrice {Object} 
   * @param repeatDiscountCode {Object} 
   * @param priceEffectiveDate {Object} 
   * @param priceExpiryDate {Object} 
   */
  constructor(xMinQty, xUom, yMinQty, yUom, price, discountCode, repeatPrice, repeatDiscountCode, priceEffectiveDate, priceExpiryDate) {
    this.xMinQty = xMinQty;
    this.xUom = xUom;
    this.yMinQty = yMinQty;
    this.yUom = yUom;
    this.price = price;
    this.discountCode = discountCode;
    this.repeatPrice = repeatPrice;
    this.repeatDiscountCode = repeatDiscountCode;
    this.priceEffectiveDate = priceEffectiveDate;
    this.priceExpiryDate = priceExpiryDate;
  }

  /**
   * Constructs a <code>ChargePrice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChargePrice} obj Optional instance to populate.
   * @return {module:model/ChargePrice} The populated <code>ChargePrice</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChargePrice();
      if (data.hasOwnProperty('xMinQty'))
        obj.xMinQty = ApiClient.convertToType(data['xMinQty'], Object);
      if (data.hasOwnProperty('xUom'))
        obj.xUom = ApiClient.convertToType(data['xUom'], Object);
      if (data.hasOwnProperty('yMinQty'))
        obj.yMinQty = ApiClient.convertToType(data['yMinQty'], Object);
      if (data.hasOwnProperty('yUom'))
        obj.yUom = ApiClient.convertToType(data['yUom'], Object);
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Object);
      if (data.hasOwnProperty('discountCode'))
        obj.discountCode = ApiClient.convertToType(data['discountCode'], Object);
      if (data.hasOwnProperty('repeatPrice'))
        obj.repeatPrice = ApiClient.convertToType(data['repeatPrice'], Object);
      if (data.hasOwnProperty('repeatDiscountCode'))
        obj.repeatDiscountCode = ApiClient.convertToType(data['repeatDiscountCode'], Object);
      if (data.hasOwnProperty('priceEffectiveDate'))
        obj.priceEffectiveDate = ApiClient.convertToType(data['priceEffectiveDate'], Object);
      if (data.hasOwnProperty('priceExpiryDate'))
        obj.priceExpiryDate = ApiClient.convertToType(data['priceExpiryDate'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} xMinQty
 */
ChargePrice.prototype.xMinQty = undefined;

/**
 * @member {Object} xUom
 */
ChargePrice.prototype.xUom = undefined;

/**
 * @member {Object} yMinQty
 */
ChargePrice.prototype.yMinQty = undefined;

/**
 * @member {Object} yUom
 */
ChargePrice.prototype.yUom = undefined;

/**
 * @member {Object} price
 */
ChargePrice.prototype.price = undefined;

/**
 * The industry discount code associated with the price
 * @member {Object} discountCode
 */
ChargePrice.prototype.discountCode = undefined;

/**
 * @member {Object} repeatPrice
 */
ChargePrice.prototype.repeatPrice = undefined;

/**
 * @member {Object} repeatDiscountCode
 */
ChargePrice.prototype.repeatDiscountCode = undefined;

/**
 * @member {Object} priceEffectiveDate
 */
ChargePrice.prototype.priceEffectiveDate = undefined;

/**
 * @member {Object} priceExpiryDate
 */
ChargePrice.prototype.priceExpiryDate = undefined;

