/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ClassType model module.
 * @module model/ClassType
 * @version 0.0.1
 */
export default class ClassType {
  /**
   * Constructs a new <code>ClassType</code>.
   * @alias module:model/ClassType
   * @class
   * @param classTypeId {Object} 
   * @param classTypeName {Object} 
   */
  constructor(classTypeId, classTypeName) {
    this.classTypeId = classTypeId;
    this.classTypeName = classTypeName;
  }

  /**
   * Constructs a <code>ClassType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClassType} obj Optional instance to populate.
   * @return {module:model/ClassType} The populated <code>ClassType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClassType();
      if (data.hasOwnProperty('classTypeId'))
        obj.classTypeId = ApiClient.convertToType(data['classTypeId'], Object);
      if (data.hasOwnProperty('classTypeName'))
        obj.classTypeName = ApiClient.convertToType(data['classTypeName'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} classTypeId
 */
ClassType.prototype.classTypeId = undefined;

/**
 * @member {Object} classTypeName
 */
ClassType.prototype.classTypeName = undefined;

