/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class ColorSystem.
 * @enum {Object}
 * @readonly
 */
const ColorSystem = {
  /**
   * value: "Cmyk"
   * @const
   */
  cmyk: "Cmyk",

  /**
   * value: "Other"
   * @const
   */
  other: "Other",

  /**
   * value: "Pms"
   * @const
   */
  pms: "Pms",

  /**
   * value: "Rgb"
   * @const
   */
  rgb: "Rgb",

  /**
   * value: "Thread"
   * @const
   */
  thread: "Thread",

  /**
   * Returns a <code>ColorSystem</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ColorSystem} The enum <code>ColorSystem</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {ColorSystem};