/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ContactDetailsInput from './ContactDetailsInput';
import ContactTypeInput from './ContactTypeInput';

/**
 * The ContactInput model module.
 * @module model/ContactInput
 * @version 0.0.1
 */
export default class ContactInput {
  /**
   * Constructs a new <code>ContactInput</code>.
   * @alias module:model/ContactInput
   * @class
   * @param contactType {module:model/ContactTypeInput} 
   * @param contactDetails {module:model/ContactDetailsInput} 
   * @param accountName {Object} 
   * @param accountNumber {Object} 
   */
  constructor(contactType, contactDetails, accountName, accountNumber) {
    this.contactType = contactType;
    this.contactDetails = contactDetails;
    this.accountName = accountName;
    this.accountNumber = accountNumber;
  }

  /**
   * Constructs a <code>ContactInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactInput} obj Optional instance to populate.
   * @return {module:model/ContactInput} The populated <code>ContactInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContactInput();
      if (data.hasOwnProperty('contactType'))
        obj.contactType = ContactTypeInput.constructFromObject(data['contactType']);
      if (data.hasOwnProperty('ContactDetails'))
        obj.contactDetails = ContactDetailsInput.constructFromObject(data['ContactDetails']);
      if (data.hasOwnProperty('accountName'))
        obj.accountName = ApiClient.convertToType(data['accountName'], Object);
      if (data.hasOwnProperty('accountNumber'))
        obj.accountNumber = ApiClient.convertToType(data['accountNumber'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/ContactTypeInput} contactType
 */
ContactInput.prototype.contactType = undefined;

/**
 * @member {module:model/ContactDetailsInput} contactDetails
 */
ContactInput.prototype.contactDetails = undefined;

/**
 * @member {Object} accountName
 */
ContactInput.prototype.accountName = undefined;

/**
 * @member {Object} accountNumber
 */
ContactInput.prototype.accountNumber = undefined;

