/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class ContactTypeInput.
 * @enum {Object}
 * @readonly
 */
const ContactTypeInput = {
  /**
   * value: "Art"
   * @const
   */
  art: "Art",

  /**
   * value: "Bill"
   * @const
   */
  bill: "Bill",

  /**
   * value: "Expeditor"
   * @const
   */
  expeditor: "Expeditor",

  /**
   * value: "Order"
   * @const
   */
  order: "Order",

  /**
   * value: "Sales"
   * @const
   */
  sales: "Sales",

  /**
   * value: "Ship"
   * @const
   */
  ship: "Ship",

  /**
   * value: "Sold"
   * @const
   */
  sold: "Sold",

  /**
   * Returns a <code>ContactTypeInput</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ContactTypeInput} The enum <code>ContactTypeInput</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {ContactTypeInput};