/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CurrencySupportedArray model module.
 * @module model/CurrencySupportedArray
 * @version 0.0.1
 */
export default class CurrencySupportedArray {
  /**
   * Constructs a new <code>CurrencySupportedArray</code>.
   * @alias module:model/CurrencySupportedArray
   * @class
   * @param currencySupported {Object} 
   */
  constructor(currencySupported) {
    this.currencySupported = currencySupported;
  }

  /**
   * Constructs a <code>CurrencySupportedArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrencySupportedArray} obj Optional instance to populate.
   * @return {module:model/CurrencySupportedArray} The populated <code>CurrencySupportedArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CurrencySupportedArray();
      if (data.hasOwnProperty('CurrencySupported'))
        obj.currencySupported = ApiClient.convertToType(data['CurrencySupported'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} currencySupported
 */
CurrencySupportedArray.prototype.currencySupported = undefined;

