/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class DecorationUomType.
 * @enum {Object}
 * @readonly
 */
const DecorationUomType = {
  /**
   * value: "Colors"
   * @const
   */
  colors: "Colors",

  /**
   * value: "Inches"
   * @const
   */
  inches: "Inches",

  /**
   * value: "Other"
   * @const
   */
  other: "Other",

  /**
   * value: "Stitches"
   * @const
   */
  stitches: "Stitches",

  /**
   * value: "SquareInches"
   * @const
   */
  squareInches: "SquareInches",

  /**
   * value: "Locations"
   * @const
   */
  locations: "Locations",

  /**
   * Returns a <code>DecorationUomType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DecorationUomType} The enum <code>DecorationUomType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {DecorationUomType};