/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DecorationMethodArray model module.
 * @module model/DecorationMethodArray
 * @version 0.0.1
 */
export default class DecorationMethodArray {
  /**
   * Constructs a new <code>DecorationMethodArray</code>.
   * @alias module:model/DecorationMethodArray
   * @class
   * @param decorationMethod {Object} 
   */
  constructor(decorationMethod) {
    this.decorationMethod = decorationMethod;
  }

  /**
   * Constructs a <code>DecorationMethodArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DecorationMethodArray} obj Optional instance to populate.
   * @return {module:model/DecorationMethodArray} The populated <code>DecorationMethodArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DecorationMethodArray();
      if (data.hasOwnProperty('DecorationMethod'))
        obj.decorationMethod = ApiClient.convertToType(data['DecorationMethod'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} decorationMethod
 */
DecorationMethodArray.prototype.decorationMethod = undefined;

