/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DigitalProofType from './DigitalProofType';

/**
 * The DigitalProofAddress model module.
 * @module model/DigitalProofAddress
 * @version 0.0.1
 */
export default class DigitalProofAddress {
  /**
   * Constructs a new <code>DigitalProofAddress</code>.
   * @alias module:model/DigitalProofAddress
   * @class
   * @param type {module:model/DigitalProofType} 
   * @param email {Object} The address that the digital proof should be sent to prior to production
   * @param lineItemGroupingId {Object} What line item group does this proof address link to
   */
  constructor(type, email, lineItemGroupingId) {
    this.type = type;
    this.email = email;
    this.lineItemGroupingId = lineItemGroupingId;
  }

  /**
   * Constructs a <code>DigitalProofAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DigitalProofAddress} obj Optional instance to populate.
   * @return {module:model/DigitalProofAddress} The populated <code>DigitalProofAddress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DigitalProofAddress();
      if (data.hasOwnProperty('type'))
        obj.type = DigitalProofType.constructFromObject(data['type']);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], Object);
      if (data.hasOwnProperty('lineItemGroupingId'))
        obj.lineItemGroupingId = ApiClient.convertToType(data['lineItemGroupingId'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/DigitalProofType} type
 */
DigitalProofAddress.prototype.type = undefined;

/**
 * The address that the digital proof should be sent to prior to production
 * @member {Object} email
 */
DigitalProofAddress.prototype.email = undefined;

/**
 * What line item group does this proof address link to
 * @member {Object} lineItemGroupingId
 */
DigitalProofAddress.prototype.lineItemGroupingId = undefined;

