/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class DimensionUoMOutput.
 * @enum {Object}
 * @readonly
 */
const DimensionUoMOutput = {
  /**
   * value: "MM"
   * @const
   */
  MM: "MM",

  /**
   * value: "CM"
   * @const
   */
  CM: "CM",

  /**
   * value: "MR"
   * @const
   */
  MR: "MR",

  /**
   * value: "IN"
   * @const
   */
  IN: "IN",

  /**
   * value: "FT"
   * @const
   */
  FT: "FT",

  /**
   * value: "YD"
   * @const
   */
  YD: "YD",

  /**
   * Returns a <code>DimensionUoMOutput</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DimensionUoMOutput} The enum <code>DimensionUoMOutput</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {DimensionUoMOutput};