/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FilterArray from './FilterArray';

/**
 * The FilterArray1 model module.
 * @module model/FilterArray1
 * @version 0.0.1
 */
export default class FilterArray1 {
  /**
   * Constructs a new <code>FilterArray1</code>.
   * @alias module:model/FilterArray1
   * @class
   * @param filterArray {module:model/FilterArray} 
   */
  constructor(filterArray) {
    this.filterArray = filterArray;
  }

  /**
   * Constructs a <code>FilterArray1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilterArray1} obj Optional instance to populate.
   * @return {module:model/FilterArray1} The populated <code>FilterArray1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FilterArray1();
      if (data.hasOwnProperty('FilterArray'))
        obj.filterArray = FilterArray.constructFromObject(data['FilterArray']);
    }
    return obj;
  }
}

/**
 * @member {module:model/FilterArray} filterArray
 */
FilterArray1.prototype.filterArray = undefined;

