/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Fob model module.
 * @module model/Fob
 * @version 0.0.1
 */
export default class Fob {
  /**
   * Constructs a new <code>Fob</code>.
   * @alias module:model/Fob
   * @class
   * @param fobId {Object} 
   * @param fobPostalCode {Object} 
   */
  constructor(fobId, fobPostalCode) {
    this.fobId = fobId;
    this.fobPostalCode = fobPostalCode;
  }

  /**
   * Constructs a <code>Fob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fob} obj Optional instance to populate.
   * @return {module:model/Fob} The populated <code>Fob</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fob();
      if (data.hasOwnProperty('fobId'))
        obj.fobId = ApiClient.convertToType(data['fobId'], Object);
      if (data.hasOwnProperty('fobPostalCode'))
        obj.fobPostalCode = ApiClient.convertToType(data['fobPostalCode'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} fobId
 */
Fob.prototype.fobId = undefined;

/**
 * @member {Object} fobPostalCode
 */
Fob.prototype.fobPostalCode = undefined;

