/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FobPointsResponse model module.
 * @module model/FobPointsResponse
 * @version 0.0.1
 */
export default class FobPointsResponse {
  /**
   * Constructs a new <code>FobPointsResponse</code>.
   * @alias module:model/FobPointsResponse
   * @class
   * @param fobPointArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(fobPointArray, errorMessage) {
    this.fobPointArray = fobPointArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>FobPointsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FobPointsResponse} obj Optional instance to populate.
   * @return {module:model/FobPointsResponse} The populated <code>FobPointsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FobPointsResponse();
      if (data.hasOwnProperty('FobPointArray'))
        obj.fobPointArray = ApiClient.convertToType(data['FobPointArray'], Object);
      if (data.hasOwnProperty('ErrorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['ErrorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} fobPointArray
 */
FobPointsResponse.prototype.fobPointArray = undefined;

/**
 * @member {Object} errorMessage
 */
FobPointsResponse.prototype.errorMessage = undefined;

