/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetInvoiceResponse model module.
 * @module model/GetInvoiceResponse
 * @version 0.0.1
 */
export default class GetInvoiceResponse {
  /**
   * Constructs a new <code>GetInvoiceResponse</code>.
   * Response object for the getInvoice method.
   * @alias module:model/GetInvoiceResponse
   * @class
   * @param invoiceArray {Object} 
   * @param serviceMessageArray {Object} 
   */
  constructor(invoiceArray, serviceMessageArray) {
    this.invoiceArray = invoiceArray;
    this.serviceMessageArray = serviceMessageArray;
  }

  /**
   * Constructs a <code>GetInvoiceResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetInvoiceResponse} obj Optional instance to populate.
   * @return {module:model/GetInvoiceResponse} The populated <code>GetInvoiceResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetInvoiceResponse();
      if (data.hasOwnProperty('InvoiceArray'))
        obj.invoiceArray = ApiClient.convertToType(data['InvoiceArray'], Object);
      if (data.hasOwnProperty('ServiceMessageArray'))
        obj.serviceMessageArray = ApiClient.convertToType(data['ServiceMessageArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} invoiceArray
 */
GetInvoiceResponse.prototype.invoiceArray = undefined;

/**
 * @member {Object} serviceMessageArray
 */
GetInvoiceResponse.prototype.serviceMessageArray = undefined;

