/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetIssueResponseV200 model module.
 * @module model/GetIssueResponseV200
 * @version 0.0.1
 */
export default class GetIssueResponseV200 {
  /**
   * Constructs a new <code>GetIssueResponseV200</code>.
   * @alias module:model/GetIssueResponseV200
   * @class
   * @param issueArray {Object} 
   * @param serviceMessageArray {Object} 
   */
  constructor(issueArray, serviceMessageArray) {
    this.issueArray = issueArray;
    this.serviceMessageArray = serviceMessageArray;
  }

  /**
   * Constructs a <code>GetIssueResponseV200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetIssueResponseV200} obj Optional instance to populate.
   * @return {module:model/GetIssueResponseV200} The populated <code>GetIssueResponseV200</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetIssueResponseV200();
      if (data.hasOwnProperty('IssueArray'))
        obj.issueArray = ApiClient.convertToType(data['IssueArray'], Object);
      if (data.hasOwnProperty('ServiceMessageArray'))
        obj.serviceMessageArray = ApiClient.convertToType(data['ServiceMessageArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} issueArray
 */
GetIssueResponseV200.prototype.issueArray = undefined;

/**
 * @member {Object} serviceMessageArray
 */
GetIssueResponseV200.prototype.serviceMessageArray = undefined;

