/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetOrderShipmentNotificationResponse model module.
 * @module model/GetOrderShipmentNotificationResponse
 * @version 0.0.1
 */
export default class GetOrderShipmentNotificationResponse {
  /**
   * Constructs a new <code>GetOrderShipmentNotificationResponse</code>.
   * Response for the GetOrderShipmentNotification method.
   * @alias module:model/GetOrderShipmentNotificationResponse
   * @class
   * @param orderShipmentNotificationArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(orderShipmentNotificationArray, errorMessage) {
    this.orderShipmentNotificationArray = orderShipmentNotificationArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>GetOrderShipmentNotificationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetOrderShipmentNotificationResponse} obj Optional instance to populate.
   * @return {module:model/GetOrderShipmentNotificationResponse} The populated <code>GetOrderShipmentNotificationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetOrderShipmentNotificationResponse();
      if (data.hasOwnProperty('OrderShipmentNotificationArray'))
        obj.orderShipmentNotificationArray = ApiClient.convertToType(data['OrderShipmentNotificationArray'], Object);
      if (data.hasOwnProperty('ErrorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['ErrorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderShipmentNotificationArray
 */
GetOrderShipmentNotificationResponse.prototype.orderShipmentNotificationArray = undefined;

/**
 * @member {Object} errorMessage
 */
GetOrderShipmentNotificationResponse.prototype.errorMessage = undefined;

