/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetProductSellableResponseV200 model module.
 * @module model/GetProductSellableResponseV200
 * @version 0.0.1
 */
export default class GetProductSellableResponseV200 {
  /**
   * Constructs a new <code>GetProductSellableResponseV200</code>.
   * @alias module:model/GetProductSellableResponseV200
   * @class
   * @param productSellableArray {Object} 
   */
  constructor(productSellableArray) {
    this.productSellableArray = productSellableArray;
  }

  /**
   * Constructs a <code>GetProductSellableResponseV200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetProductSellableResponseV200} obj Optional instance to populate.
   * @return {module:model/GetProductSellableResponseV200} The populated <code>GetProductSellableResponseV200</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetProductSellableResponseV200();
      if (data.hasOwnProperty('ProductSellableArray'))
        obj.productSellableArray = ApiClient.convertToType(data['ProductSellableArray'], Object);
      if (data.hasOwnProperty('ServiceMessageArray'))
        obj.serviceMessageArray = ApiClient.convertToType(data['ServiceMessageArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productSellableArray
 */
GetProductSellableResponseV200.prototype.productSellableArray = undefined;

/**
 * @member {Object} serviceMessageArray
 */
GetProductSellableResponseV200.prototype.serviceMessageArray = undefined;

