/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The HTTPValidationError model module.
 * @module model/HTTPValidationError
 * @version 0.0.1
 */
export default class HTTPValidationError {
  /**
   * Constructs a new <code>HTTPValidationError</code>.
   * @alias module:model/HTTPValidationError
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HTTPValidationError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HTTPValidationError} obj Optional instance to populate.
   * @return {module:model/HTTPValidationError} The populated <code>HTTPValidationError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HTTPValidationError();
      if (data.hasOwnProperty('detail'))
        obj.detail = ApiClient.convertToType(data['detail'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} detail
 */
HTTPValidationError.prototype.detail = undefined;

