/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InventoryLevelsResponseV200 model module.
 * @module model/InventoryLevelsResponseV200
 * @version 0.0.1
 */
export default class InventoryLevelsResponseV200 {
  /**
   * Constructs a new <code>InventoryLevelsResponseV200</code>.
   * @alias module:model/InventoryLevelsResponseV200
   * @class
   * @param inventory {Object} 
   * @param serviceMessageArray {Object} 
   */
  constructor(inventory, serviceMessageArray) {
    this.inventory = inventory;
    this.serviceMessageArray = serviceMessageArray;
  }

  /**
   * Constructs a <code>InventoryLevelsResponseV200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InventoryLevelsResponseV200} obj Optional instance to populate.
   * @return {module:model/InventoryLevelsResponseV200} The populated <code>InventoryLevelsResponseV200</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InventoryLevelsResponseV200();
      if (data.hasOwnProperty('Inventory'))
        obj.inventory = ApiClient.convertToType(data['Inventory'], Object);
      if (data.hasOwnProperty('ServiceMessageArray'))
        obj.serviceMessageArray = ApiClient.convertToType(data['ServiceMessageArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} inventory
 */
InventoryLevelsResponseV200.prototype.inventory = undefined;

/**
 * @member {Object} serviceMessageArray
 */
InventoryLevelsResponseV200.prototype.serviceMessageArray = undefined;

