/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InvoiceArray model module.
 * @module model/InvoiceArray
 * @version 0.0.1
 */
export default class InvoiceArray {
  /**
   * Constructs a new <code>InvoiceArray</code>.
   * @alias module:model/InvoiceArray
   * @class
   * @param invoice {Object} 
   */
  constructor(invoice) {
    this.invoice = invoice;
  }

  /**
   * Constructs a <code>InvoiceArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoiceArray} obj Optional instance to populate.
   * @return {module:model/InvoiceArray} The populated <code>InvoiceArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InvoiceArray();
      if (data.hasOwnProperty('Invoice'))
        obj.invoice = ApiClient.convertToType(data['Invoice'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} invoice
 */
InvoiceArray.prototype.invoice = undefined;

