/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class IssueStatus.
 * @enum {Object}
 * @readonly
 */
const IssueStatus = {
  /**
   * value: "Pending"
   * @const
   */
  pending: "Pending",

  /**
   * value: "Open"
   * @const
   */
  open: "Open",

  /**
   * value: "Closed"
   * @const
   */
  closed: "Closed",

  /**
   * Returns a <code>IssueStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/IssueStatus} The enum <code>IssueStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {IssueStatus};