/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LayerOrStop model module.
 * @module model/LayerOrStop
 * @version 0.0.1
 */
export default class LayerOrStop {
  /**
   * Constructs a new <code>LayerOrStop</code>.
   * @alias module:model/LayerOrStop
   * @class
   * @param nameOrNumber {Object} The name or number of the layer or stop
   * @param description {Object} A human readable description of the layer
   * @param color {Object} The color value that corresponds to the colorSystem defined
   */
  constructor(nameOrNumber, description, color) {
    this.nameOrNumber = nameOrNumber;
    this.description = description;
    this.color = color;
  }

  /**
   * Constructs a <code>LayerOrStop</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LayerOrStop} obj Optional instance to populate.
   * @return {module:model/LayerOrStop} The populated <code>LayerOrStop</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LayerOrStop();
      if (data.hasOwnProperty('nameOrNumber'))
        obj.nameOrNumber = ApiClient.convertToType(data['nameOrNumber'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('color'))
        obj.color = ApiClient.convertToType(data['color'], Object);
    }
    return obj;
  }
}

/**
 * The name or number of the layer or stop
 * @member {Object} nameOrNumber
 */
LayerOrStop.prototype.nameOrNumber = undefined;

/**
 * A human readable description of the layer
 * @member {Object} description
 */
LayerOrStop.prototype.description = undefined;

/**
 * The color value that corresponds to the colorSystem defined
 * @member {Object} color
 */
LayerOrStop.prototype.color = undefined;

