/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LocationArrayInput model module.
 * @module model/LocationArrayInput
 * @version 0.0.1
 */
export default class LocationArrayInput {
  /**
   * Constructs a new <code>LocationArrayInput</code>.
   * An array of Decoration Location Information.  This array should be populated with information from the supplier’s PromoStandards Product Pricing and Configuration service
   * @alias module:model/LocationArrayInput
   * @class
   * @param location {Object} 
   */
  constructor(location) {
    this.location = location;
  }

  /**
   * Constructs a <code>LocationArrayInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LocationArrayInput} obj Optional instance to populate.
   * @return {module:model/LocationArrayInput} The populated <code>LocationArrayInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LocationArrayInput();
      if (data.hasOwnProperty('Location'))
        obj.location = ApiClient.convertToType(data['Location'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} location
 */
LocationArrayInput.prototype.location = undefined;

