/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LocationDecoration model module.
 * @module model/LocationDecoration
 * @version 0.0.1
 */
export default class LocationDecoration {
  /**
   * Constructs a new <code>LocationDecoration</code>.
   * @alias module:model/LocationDecoration
   * @class
   * @param locationName {Object} 
   * @param maxImprintColors {Object} 
   * @param decorationName {Object} 
   * @param locationDecorationComboDefault {Object} 
   * @param priceIncludes {Object} 
   */
  constructor(locationName, maxImprintColors, decorationName, locationDecorationComboDefault, priceIncludes) {
    this.locationName = locationName;
    this.maxImprintColors = maxImprintColors;
    this.decorationName = decorationName;
    this.locationDecorationComboDefault = locationDecorationComboDefault;
    this.priceIncludes = priceIncludes;
  }

  /**
   * Constructs a <code>LocationDecoration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LocationDecoration} obj Optional instance to populate.
   * @return {module:model/LocationDecoration} The populated <code>LocationDecoration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LocationDecoration();
      if (data.hasOwnProperty('locationName'))
        obj.locationName = ApiClient.convertToType(data['locationName'], Object);
      if (data.hasOwnProperty('maxImprintColors'))
        obj.maxImprintColors = ApiClient.convertToType(data['maxImprintColors'], Object);
      if (data.hasOwnProperty('decorationName'))
        obj.decorationName = ApiClient.convertToType(data['decorationName'], Object);
      if (data.hasOwnProperty('locationDecorationComboDefault'))
        obj.locationDecorationComboDefault = ApiClient.convertToType(data['locationDecorationComboDefault'], Object);
      if (data.hasOwnProperty('priceIncludes'))
        obj.priceIncludes = ApiClient.convertToType(data['priceIncludes'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} locationName
 */
LocationDecoration.prototype.locationName = undefined;

/**
 * @member {Object} maxImprintColors
 */
LocationDecoration.prototype.maxImprintColors = undefined;

/**
 * @member {Object} decorationName
 */
LocationDecoration.prototype.decorationName = undefined;

/**
 * @member {Object} locationDecorationComboDefault
 */
LocationDecoration.prototype.locationDecorationComboDefault = undefined;

/**
 * @member {Object} priceIncludes
 */
LocationDecoration.prototype.priceIncludes = undefined;

