/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MediaDateModifiedArray model module.
 * @module model/MediaDateModifiedArray
 * @version 0.0.1
 */
export default class MediaDateModifiedArray {
  /**
   * Constructs a new <code>MediaDateModifiedArray</code>.
   * @alias module:model/MediaDateModifiedArray
   * @class
   * @param mediaDateModified {Object} 
   */
  constructor(mediaDateModified) {
    this.mediaDateModified = mediaDateModified;
  }

  /**
   * Constructs a <code>MediaDateModifiedArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaDateModifiedArray} obj Optional instance to populate.
   * @return {module:model/MediaDateModifiedArray} The populated <code>MediaDateModifiedArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaDateModifiedArray();
      if (data.hasOwnProperty('MediaDateModified'))
        obj.mediaDateModified = ApiClient.convertToType(data['MediaDateModified'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} mediaDateModified
 */
MediaDateModifiedArray.prototype.mediaDateModified = undefined;

