/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MediaContentArray model module.
 * @module model/MediaContentArray
 * @version 0.0.1
 */
export default class MediaContentArray {
  /**
   * Constructs a new <code>MediaContentArray</code>.
   * @alias module:model/MediaContentArray
   * @class
   * @param mediaContent {Object} 
   */
  constructor(mediaContent) {
    this.mediaContent = mediaContent;
  }

  /**
   * Constructs a <code>MediaContentArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaContentArray} obj Optional instance to populate.
   * @return {module:model/MediaContentArray} The populated <code>MediaContentArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaContentArray();
      if (data.hasOwnProperty('MediaContent'))
        obj.mediaContent = ApiClient.convertToType(data['MediaContent'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} mediaContent
 */
MediaContentArray.prototype.mediaContent = undefined;

