/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MediaContentDetailsResponse model module.
 * @module model/MediaContentDetailsResponse
 * @version 0.0.1
 */
export default class MediaContentDetailsResponse {
  /**
   * Constructs a new <code>MediaContentDetailsResponse</code>.
   * @alias module:model/MediaContentDetailsResponse
   * @class
   * @param mediaContentArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(mediaContentArray, errorMessage) {
    this.mediaContentArray = mediaContentArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>MediaContentDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaContentDetailsResponse} obj Optional instance to populate.
   * @return {module:model/MediaContentDetailsResponse} The populated <code>MediaContentDetailsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaContentDetailsResponse();
      if (data.hasOwnProperty('MediaContentArray'))
        obj.mediaContentArray = ApiClient.convertToType(data['MediaContentArray'], Object);
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} mediaContentArray
 */
MediaContentDetailsResponse.prototype.mediaContentArray = undefined;

/**
 * @member {Object} errorMessage
 */
MediaContentDetailsResponse.prototype.errorMessage = undefined;

