/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class MediaType.
 * @enum {Object}
 * @readonly
 */
const MediaType = {
  /**
   * value: "Image"
   * @const
   */
  image: "Image",

  /**
   * value: "Video"
   * @const
   */
  video: "Video",

  /**
   * value: "Audio"
   * @const
   */
  audio: "Audio",

  /**
   * value: "Document"
   * @const
   */
  document: "Document",

  /**
   * Returns a <code>MediaType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/MediaType} The enum <code>MediaType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {MediaType};