/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ModelPackage model module.
 * @module model/ModelPackage
 * @version 0.0.1
 */
export default class ModelPackage {
  /**
   * Constructs a new <code>ModelPackage</code>.
   * @alias module:model/ModelPackage
   * @class
   * @param id {Object} 
   * @param trackingNumber {Object} 
   * @param shipmentDate {Object} 
   * @param dimUOM {Object} 
   * @param length {Object} 
   * @param width {Object} 
   * @param height {Object} 
   * @param weightUOM {Object} 
   * @param weight {Object} 
   * @param carrier {Object} 
   * @param shipmentMethod {Object} 
   * @param shippingAccount {Object} 
   * @param shipmentTerms {Object} 
   * @param itemArray {Object} 
   */
  constructor(id, trackingNumber, shipmentDate, dimUOM, length, width, height, weightUOM, weight, carrier, shipmentMethod, shippingAccount, shipmentTerms, itemArray) {
    this.id = id;
    this.trackingNumber = trackingNumber;
    this.shipmentDate = shipmentDate;
    this.dimUOM = dimUOM;
    this.length = length;
    this.width = width;
    this.height = height;
    this.weightUOM = weightUOM;
    this.weight = weight;
    this.carrier = carrier;
    this.shipmentMethod = shipmentMethod;
    this.shippingAccount = shippingAccount;
    this.shipmentTerms = shipmentTerms;
    this.itemArray = itemArray;
  }

  /**
   * Constructs a <code>ModelPackage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelPackage} obj Optional instance to populate.
   * @return {module:model/ModelPackage} The populated <code>ModelPackage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelPackage();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], Object);
      if (data.hasOwnProperty('trackingNumber'))
        obj.trackingNumber = ApiClient.convertToType(data['trackingNumber'], Object);
      if (data.hasOwnProperty('shipmentDate'))
        obj.shipmentDate = ApiClient.convertToType(data['shipmentDate'], Object);
      if (data.hasOwnProperty('dimUOM'))
        obj.dimUOM = ApiClient.convertToType(data['dimUOM'], Object);
      if (data.hasOwnProperty('length'))
        obj.length = ApiClient.convertToType(data['length'], Object);
      if (data.hasOwnProperty('width'))
        obj.width = ApiClient.convertToType(data['width'], Object);
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], Object);
      if (data.hasOwnProperty('weightUOM'))
        obj.weightUOM = ApiClient.convertToType(data['weightUOM'], Object);
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], Object);
      if (data.hasOwnProperty('carrier'))
        obj.carrier = ApiClient.convertToType(data['carrier'], Object);
      if (data.hasOwnProperty('shipmentMethod'))
        obj.shipmentMethod = ApiClient.convertToType(data['shipmentMethod'], Object);
      if (data.hasOwnProperty('shippingAccount'))
        obj.shippingAccount = ApiClient.convertToType(data['shippingAccount'], Object);
      if (data.hasOwnProperty('shipmentTerms'))
        obj.shipmentTerms = ApiClient.convertToType(data['shipmentTerms'], Object);
      if (data.hasOwnProperty('ItemArray'))
        obj.itemArray = ApiClient.convertToType(data['ItemArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} id
 */
ModelPackage.prototype.id = undefined;

/**
 * @member {Object} trackingNumber
 */
ModelPackage.prototype.trackingNumber = undefined;

/**
 * @member {Object} shipmentDate
 */
ModelPackage.prototype.shipmentDate = undefined;

/**
 * @member {Object} dimUOM
 */
ModelPackage.prototype.dimUOM = undefined;

/**
 * @member {Object} length
 */
ModelPackage.prototype.length = undefined;

/**
 * @member {Object} width
 */
ModelPackage.prototype.width = undefined;

/**
 * @member {Object} height
 */
ModelPackage.prototype.height = undefined;

/**
 * @member {Object} weightUOM
 */
ModelPackage.prototype.weightUOM = undefined;

/**
 * @member {Object} weight
 */
ModelPackage.prototype.weight = undefined;

/**
 * @member {Object} carrier
 */
ModelPackage.prototype.carrier = undefined;

/**
 * @member {Object} shipmentMethod
 */
ModelPackage.prototype.shipmentMethod = undefined;

/**
 * @member {Object} shippingAccount
 */
ModelPackage.prototype.shippingAccount = undefined;

/**
 * @member {Object} shipmentTerms
 */
ModelPackage.prototype.shipmentTerms = undefined;

/**
 * @member {Object} itemArray
 */
ModelPackage.prototype.itemArray = undefined;

