/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderStatusDetailsResponse model module.
 * @module model/OrderStatusDetailsResponse
 * @version 0.0.1
 */
export default class OrderStatusDetailsResponse {
  /**
   * Constructs a new <code>OrderStatusDetailsResponse</code>.
   * @alias module:model/OrderStatusDetailsResponse
   * @class
   * @param orderStatusArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(orderStatusArray, errorMessage) {
    this.orderStatusArray = orderStatusArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>OrderStatusDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderStatusDetailsResponse} obj Optional instance to populate.
   * @return {module:model/OrderStatusDetailsResponse} The populated <code>OrderStatusDetailsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderStatusDetailsResponse();
      if (data.hasOwnProperty('OrderStatusArray'))
        obj.orderStatusArray = ApiClient.convertToType(data['OrderStatusArray'], Object);
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderStatusArray
 */
OrderStatusDetailsResponse.prototype.orderStatusArray = undefined;

/**
 * @member {Object} errorMessage
 */
OrderStatusDetailsResponse.prototype.errorMessage = undefined;

