/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderStatusTypesResponse model module.
 * @module model/OrderStatusTypesResponse
 * @version 0.0.1
 */
export default class OrderStatusTypesResponse {
  /**
   * Constructs a new <code>OrderStatusTypesResponse</code>.
   * Response from getOrderStatusTypes
   * @alias module:model/OrderStatusTypesResponse
   * @class
   * @param statusArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(statusArray, errorMessage) {
    this.statusArray = statusArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>OrderStatusTypesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderStatusTypesResponse} obj Optional instance to populate.
   * @return {module:model/OrderStatusTypesResponse} The populated <code>OrderStatusTypesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderStatusTypesResponse();
      if (data.hasOwnProperty('StatusArray'))
        obj.statusArray = ApiClient.convertToType(data['StatusArray'], Object);
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} statusArray
 */
OrderStatusTypesResponse.prototype.statusArray = undefined;

/**
 * @member {Object} errorMessage
 */
OrderStatusTypesResponse.prototype.errorMessage = undefined;

