/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PartInventoryArray model module.
 * @module model/PartInventoryArray
 * @version 0.0.1
 */
export default class PartInventoryArray {
  /**
   * Constructs a new <code>PartInventoryArray</code>.
   * @alias module:model/PartInventoryArray
   * @class
   * @param partInventory {Object} 
   */
  constructor(partInventory) {
    this.partInventory = partInventory;
  }

  /**
   * Constructs a <code>PartInventoryArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartInventoryArray} obj Optional instance to populate.
   * @return {module:model/PartInventoryArray} The populated <code>PartInventoryArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartInventoryArray();
      if (data.hasOwnProperty('PartInventory'))
        obj.partInventory = ApiClient.convertToType(data['PartInventory'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} partInventory
 */
PartInventoryArray.prototype.partInventory = undefined;

