/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PartColorArray model module.
 * @module model/PartColorArray
 * @version 0.0.1
 */
export default class PartColorArray {
  /**
   * Constructs a new <code>PartColorArray</code>.
   * @alias module:model/PartColorArray
   * @class
   * @param partColor {Object} 
   */
  constructor(partColor) {
    this.partColor = partColor;
  }

  /**
   * Constructs a <code>PartColorArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartColorArray} obj Optional instance to populate.
   * @return {module:model/PartColorArray} The populated <code>PartColorArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartColorArray();
      if (data.hasOwnProperty('partColor'))
        obj.partColor = ApiClient.convertToType(data['partColor'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} partColor
 */
PartColorArray.prototype.partColor = undefined;

