/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PartPriceArray model module.
 * @module model/PartPriceArray
 * @version 0.0.1
 */
export default class PartPriceArray {
  /**
   * Constructs a new <code>PartPriceArray</code>.
   * @alias module:model/PartPriceArray
   * @class
   * @param partPrice {Object} 
   */
  constructor(partPrice) {
    this.partPrice = partPrice;
  }

  /**
   * Constructs a <code>PartPriceArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartPriceArray} obj Optional instance to populate.
   * @return {module:model/PartPriceArray} The populated <code>PartPriceArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartPriceArray();
      if (data.hasOwnProperty('PartPrice'))
        obj.partPrice = ApiClient.convertToType(data['PartPrice'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} partPrice
 */
PartPriceArray.prototype.partPrice = undefined;

