/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Color from './Color';

/**
 * The PrimaryColor model module.
 * @module model/PrimaryColor
 * @version 0.0.1
 */
export default class PrimaryColor {
  /**
   * Constructs a new <code>PrimaryColor</code>.
   * @alias module:model/PrimaryColor
   * @class
   * @param color {module:model/Color} 
   */
  constructor(color) {
    this.color = color;
  }

  /**
   * Constructs a <code>PrimaryColor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrimaryColor} obj Optional instance to populate.
   * @return {module:model/PrimaryColor} The populated <code>PrimaryColor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrimaryColor();
      if (data.hasOwnProperty('Color'))
        obj.color = Color.constructFromObject(data['Color']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Color} color
 */
PrimaryColor.prototype.color = undefined;

