/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DimensionUoMOutput from './DimensionUoMOutput';
import WeightUOM from './WeightUOM';

/**
 * The ProductPackage model module.
 * @module model/ProductPackage
 * @version 0.0.1
 */
export default class ProductPackage {
  /**
   * Constructs a new <code>ProductPackage</code>.
   * @alias module:model/ProductPackage
   * @class
   * @param _default {Object} 
   * @param packageType {Object} 
   * @param description {Object} 
   * @param quantity {Object} 
   * @param dimensionUom {module:model/DimensionUoMOutput} 
   * @param depth {Object} 
   * @param height {Object} 
   * @param width {Object} 
   * @param weightUom {module:model/WeightUOM} 
   * @param weight {Object} 
   */
  constructor(_default, packageType, description, quantity, dimensionUom, depth, height, width, weightUom, weight) {
    this._default = _default;
    this.packageType = packageType;
    this.description = description;
    this.quantity = quantity;
    this.dimensionUom = dimensionUom;
    this.depth = depth;
    this.height = height;
    this.width = width;
    this.weightUom = weightUom;
    this.weight = weight;
  }

  /**
   * Constructs a <code>ProductPackage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductPackage} obj Optional instance to populate.
   * @return {module:model/ProductPackage} The populated <code>ProductPackage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductPackage();
      if (data.hasOwnProperty('default'))
        obj._default = ApiClient.convertToType(data['default'], Object);
      if (data.hasOwnProperty('packageType'))
        obj.packageType = ApiClient.convertToType(data['packageType'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
      if (data.hasOwnProperty('dimensionUom'))
        obj.dimensionUom = DimensionUoMOutput.constructFromObject(data['dimensionUom']);
      if (data.hasOwnProperty('depth'))
        obj.depth = ApiClient.convertToType(data['depth'], Object);
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], Object);
      if (data.hasOwnProperty('width'))
        obj.width = ApiClient.convertToType(data['width'], Object);
      if (data.hasOwnProperty('weightUom'))
        obj.weightUom = WeightUoM.constructFromObject(data['weightUom']);
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} _default
 */
ProductPackage.prototype._default = undefined;

/**
 * @member {Object} packageType
 */
ProductPackage.prototype.packageType = undefined;

/**
 * @member {Object} description
 */
ProductPackage.prototype.description = undefined;

/**
 * @member {Object} quantity
 */
ProductPackage.prototype.quantity = undefined;

/**
 * @member {module:model/DimensionUoMOutput} dimensionUom
 */
ProductPackage.prototype.dimensionUom = undefined;

/**
 * @member {Object} depth
 */
ProductPackage.prototype.depth = undefined;

/**
 * @member {Object} height
 */
ProductPackage.prototype.height = undefined;

/**
 * @member {Object} width
 */
ProductPackage.prototype.width = undefined;

/**
 * @member {module:model/WeightUoM} weightUom
 */
ProductPackage.prototype.weightUom = undefined;

/**
 * @member {Object} weight
 */
ProductPackage.prototype.weight = undefined;

