/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductMarketingPointArray model module.
 * @module model/ProductMarketingPointArray
 * @version 0.0.1
 */
export default class ProductMarketingPointArray {
  /**
   * Constructs a new <code>ProductMarketingPointArray</code>.
   * @alias module:model/ProductMarketingPointArray
   * @class
   * @param productMarketingPoint {Object} 
   */
  constructor(productMarketingPoint) {
    this.productMarketingPoint = productMarketingPoint;
  }

  /**
   * Constructs a <code>ProductMarketingPointArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductMarketingPointArray} obj Optional instance to populate.
   * @return {module:model/ProductMarketingPointArray} The populated <code>ProductMarketingPointArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductMarketingPointArray();
      if (data.hasOwnProperty('ProductMarketingPoint'))
        obj.productMarketingPoint = ApiClient.convertToType(data['ProductMarketingPoint'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productMarketingPoint
 */
ProductMarketingPointArray.prototype.productMarketingPoint = undefined;

