/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductCategoryArray model module.
 * @module model/ProductCategoryArray
 * @version 0.0.1
 */
export default class ProductCategoryArray {
  /**
   * Constructs a new <code>ProductCategoryArray</code>.
   * @alias module:model/ProductCategoryArray
   * @class
   * @param productCategory {Object} 
   */
  constructor(productCategory) {
    this.productCategory = productCategory;
  }

  /**
   * Constructs a <code>ProductCategoryArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductCategoryArray} obj Optional instance to populate.
   * @return {module:model/ProductCategoryArray} The populated <code>ProductCategoryArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductCategoryArray();
      if (data.hasOwnProperty('ProductCategory'))
        obj.productCategory = ApiClient.convertToType(data['ProductCategory'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productCategory
 */
ProductCategoryArray.prototype.productCategory = undefined;

