/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductPriceArray model module.
 * @module model/ProductPriceArray
 * @version 0.0.1
 */
export default class ProductPriceArray {
  /**
   * Constructs a new <code>ProductPriceArray</code>.
   * @alias module:model/ProductPriceArray
   * @class
   * @param productPrice {Object} 
   */
  constructor(productPrice) {
    this.productPrice = productPrice;
  }

  /**
   * Constructs a <code>ProductPriceArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductPriceArray} obj Optional instance to populate.
   * @return {module:model/ProductPriceArray} The populated <code>ProductPriceArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductPriceArray();
      if (data.hasOwnProperty('ProductPrice'))
        obj.productPrice = ApiClient.convertToType(data['ProductPrice'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productPrice
 */
ProductPriceArray.prototype.productPrice = undefined;

