/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductCloseOutResponseV100 model module.
 * @module model/ProductCloseOutResponseV100
 * @version 0.0.1
 */
export default class ProductCloseOutResponseV100 {
  /**
   * Constructs a new <code>ProductCloseOutResponseV100</code>.
   * @alias module:model/ProductCloseOutResponseV100
   * @class
   * @param productCloseOutArray {Object} 
   * @param errorMessage {Object} 
   */
  constructor(productCloseOutArray, errorMessage) {
    this.productCloseOutArray = productCloseOutArray;
    this.errorMessage = errorMessage;
  }

  /**
   * Constructs a <code>ProductCloseOutResponseV100</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductCloseOutResponseV100} obj Optional instance to populate.
   * @return {module:model/ProductCloseOutResponseV100} The populated <code>ProductCloseOutResponseV100</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductCloseOutResponseV100();
      if (data.hasOwnProperty('ProductCloseOutArray'))
        obj.productCloseOutArray = ApiClient.convertToType(data['ProductCloseOutArray'], Object);
      if (data.hasOwnProperty('ErrorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['ErrorMessage'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productCloseOutArray
 */
ProductCloseOutResponseV100.prototype.productCloseOutArray = undefined;

/**
 * @member {Object} errorMessage
 */
ProductCloseOutResponseV100.prototype.errorMessage = undefined;

