/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ProductPriceArray from './ProductPriceArray';

/**
 * The ProductPriceGroup model module.
 * @module model/ProductPriceGroup
 * @version 0.0.1
 */
export default class ProductPriceGroup {
  /**
   * Constructs a new <code>ProductPriceGroup</code>.
   * @alias module:model/ProductPriceGroup
   * @class
   * @param groupName {Object} 
   * @param currency {Object} 
   * @param description {Object} 
   * @param productPriceArray {module:model/ProductPriceArray} 
   */
  constructor(groupName, currency, description, productPriceArray) {
    this.groupName = groupName;
    this.currency = currency;
    this.description = description;
    this.productPriceArray = productPriceArray;
  }

  /**
   * Constructs a <code>ProductPriceGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductPriceGroup} obj Optional instance to populate.
   * @return {module:model/ProductPriceGroup} The populated <code>ProductPriceGroup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductPriceGroup();
      if (data.hasOwnProperty('groupName'))
        obj.groupName = ApiClient.convertToType(data['groupName'], Object);
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('ProductPriceArray'))
        obj.productPriceArray = ProductPriceArray.constructFromObject(data['ProductPriceArray']);
    }
    return obj;
  }
}

/**
 * @member {Object} groupName
 */
ProductPriceGroup.prototype.groupName = undefined;

/**
 * @member {Object} currency
 */
ProductPriceGroup.prototype.currency = undefined;

/**
 * @member {Object} description
 */
ProductPriceGroup.prototype.description = undefined;

/**
 * @member {module:model/ProductPriceArray} productPriceArray
 */
ProductPriceGroup.prototype.productPriceArray = undefined;

