/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductDateModified model module.
 * @module model/ProductDateModified
 * @version 0.0.1
 */
export default class ProductDateModified {
  /**
   * Constructs a new <code>ProductDateModified</code>.
   * @alias module:model/ProductDateModified
   * @class
   * @param productId {Object} 
   * @param partId {Object} 
   */
  constructor(productId, partId) {
    this.productId = productId;
    this.partId = partId;
  }

  /**
   * Constructs a <code>ProductDateModified</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductDateModified} obj Optional instance to populate.
   * @return {module:model/ProductDateModified} The populated <code>ProductDateModified</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductDateModified();
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], Object);
      if (data.hasOwnProperty('partId'))
        obj.partId = ApiClient.convertToType(data['partId'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productId
 */
ProductDateModified.prototype.productId = undefined;

/**
 * @member {Object} partId
 */
ProductDateModified.prototype.partId = undefined;

