/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PsDomainModelProductDataCommonFobPointArray model module.
 * @module model/PsDomainModelProductDataCommonFobPointArray
 * @version 0.0.1
 */
export default class PsDomainModelProductDataCommonFobPointArray {
  /**
   * Constructs a new <code>PsDomainModelProductDataCommonFobPointArray</code>.
   * @alias module:model/PsDomainModelProductDataCommonFobPointArray
   * @class
   * @param fobPoint {Object} 
   */
  constructor(fobPoint) {
    this.fobPoint = fobPoint;
  }

  /**
   * Constructs a <code>PsDomainModelProductDataCommonFobPointArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsDomainModelProductDataCommonFobPointArray} obj Optional instance to populate.
   * @return {module:model/PsDomainModelProductDataCommonFobPointArray} The populated <code>PsDomainModelProductDataCommonFobPointArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PsDomainModelProductDataCommonFobPointArray();
      if (data.hasOwnProperty('FobPoint'))
        obj.fobPoint = ApiClient.convertToType(data['FobPoint'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} fobPoint
 */
PsDomainModelProductDataCommonFobPointArray.prototype.fobPoint = undefined;

