/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class PsDomainModelOsnCommonQueryType.
 * @enum {Object}
 * @readonly
 */
const PsDomainModelOsnCommonQueryType = {
  /**
   * value: "1"
   * @const
   */
  _1: "1",

  /**
   * value: "2"
   * @const
   */
  _2: "2",

  /**
   * value: "3"
   * @const
   */
  _3: "3",

  /**
   * Returns a <code>PsDomainModelOsnCommonQueryType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/PsDomainModelOsnCommonQueryType} The enum <code>PsDomainModelOsnCommonQueryType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {PsDomainModelOsnCommonQueryType};