/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PsDomainModelOrderStatusV100OrderStatusDetail model module.
 * @module model/PsDomainModelOrderStatusV100OrderStatusDetail
 * @version 0.0.1
 */
export default class PsDomainModelOrderStatusV100OrderStatusDetail {
  /**
   * Constructs a new <code>PsDomainModelOrderStatusV100OrderStatusDetail</code>.
   * @alias module:model/PsDomainModelOrderStatusV100OrderStatusDetail
   * @class
   * @param factoryOrderNumber {Object} 
   * @param statusID {Object} 
   * @param statusName {Object} 
   * @param validTimestamp {Object} 
   * @param expectedShipDate {Object} 
   * @param expectedDeliveryDate {Object} 
   * @param responseToArray {Object} 
   * @param additionalExplanation {Object} 
   */
  constructor(factoryOrderNumber, statusID, statusName, validTimestamp, expectedShipDate, expectedDeliveryDate, responseToArray, additionalExplanation) {
    this.factoryOrderNumber = factoryOrderNumber;
    this.statusID = statusID;
    this.statusName = statusName;
    this.validTimestamp = validTimestamp;
    this.expectedShipDate = expectedShipDate;
    this.expectedDeliveryDate = expectedDeliveryDate;
    this.responseToArray = responseToArray;
    this.additionalExplanation = additionalExplanation;
  }

  /**
   * Constructs a <code>PsDomainModelOrderStatusV100OrderStatusDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsDomainModelOrderStatusV100OrderStatusDetail} obj Optional instance to populate.
   * @return {module:model/PsDomainModelOrderStatusV100OrderStatusDetail} The populated <code>PsDomainModelOrderStatusV100OrderStatusDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PsDomainModelOrderStatusV100OrderStatusDetail();
      if (data.hasOwnProperty('factoryOrderNumber'))
        obj.factoryOrderNumber = ApiClient.convertToType(data['factoryOrderNumber'], Object);
      if (data.hasOwnProperty('statusID'))
        obj.statusID = ApiClient.convertToType(data['statusID'], Object);
      if (data.hasOwnProperty('statusName'))
        obj.statusName = ApiClient.convertToType(data['statusName'], Object);
      if (data.hasOwnProperty('responseRequired'))
        obj.responseRequired = ApiClient.convertToType(data['responseRequired'], Object);
      if (data.hasOwnProperty('validTimestamp'))
        obj.validTimestamp = ApiClient.convertToType(data['validTimestamp'], Object);
      if (data.hasOwnProperty('expectedShipDate'))
        obj.expectedShipDate = ApiClient.convertToType(data['expectedShipDate'], Object);
      if (data.hasOwnProperty('expectedDeliveryDate'))
        obj.expectedDeliveryDate = ApiClient.convertToType(data['expectedDeliveryDate'], Object);
      if (data.hasOwnProperty('ResponseToArray'))
        obj.responseToArray = ApiClient.convertToType(data['ResponseToArray'], Object);
      if (data.hasOwnProperty('additionalExplanation'))
        obj.additionalExplanation = ApiClient.convertToType(data['additionalExplanation'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} factoryOrderNumber
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.factoryOrderNumber = undefined;

/**
 * @member {Object} statusID
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.statusID = undefined;

/**
 * @member {Object} statusName
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.statusName = undefined;

/**
 * @member {Object} responseRequired
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.responseRequired = undefined;

/**
 * @member {Object} validTimestamp
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.validTimestamp = undefined;

/**
 * @member {Object} expectedShipDate
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.expectedShipDate = undefined;

/**
 * @member {Object} expectedDeliveryDate
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.expectedDeliveryDate = undefined;

/**
 * @member {Object} responseToArray
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.responseToArray = undefined;

/**
 * @member {Object} additionalExplanation
 */
PsDomainModelOrderStatusV100OrderStatusDetail.prototype.additionalExplanation = undefined;

