/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PsDomainModelMediaContentDecorationArray model module.
 * @module model/PsDomainModelMediaContentDecorationArray
 * @version 0.0.1
 */
export default class PsDomainModelMediaContentDecorationArray {
  /**
   * Constructs a new <code>PsDomainModelMediaContentDecorationArray</code>.
   * @alias module:model/PsDomainModelMediaContentDecorationArray
   * @class
   * @param decoration {Object} 
   */
  constructor(decoration) {
    this.decoration = decoration;
  }

  /**
   * Constructs a <code>PsDomainModelMediaContentDecorationArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsDomainModelMediaContentDecorationArray} obj Optional instance to populate.
   * @return {module:model/PsDomainModelMediaContentDecorationArray} The populated <code>PsDomainModelMediaContentDecorationArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PsDomainModelMediaContentDecorationArray();
      if (data.hasOwnProperty('Decoration'))
        obj.decoration = ApiClient.convertToType(data['Decoration'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} decoration
 */
PsDomainModelMediaContentDecorationArray.prototype.decoration = undefined;

