/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PsDomainModelOrderStatusV100OrderStatusArray model module.
 * @module model/PsDomainModelOrderStatusV100OrderStatusArray
 * @version 0.0.1
 */
export default class PsDomainModelOrderStatusV100OrderStatusArray {
  /**
   * Constructs a new <code>PsDomainModelOrderStatusV100OrderStatusArray</code>.
   * @alias module:model/PsDomainModelOrderStatusV100OrderStatusArray
   * @class
   * @param orderStatus {Object} 
   */
  constructor(orderStatus) {
    this.orderStatus = orderStatus;
  }

  /**
   * Constructs a <code>PsDomainModelOrderStatusV100OrderStatusArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsDomainModelOrderStatusV100OrderStatusArray} obj Optional instance to populate.
   * @return {module:model/PsDomainModelOrderStatusV100OrderStatusArray} The populated <code>PsDomainModelOrderStatusV100OrderStatusArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PsDomainModelOrderStatusV100OrderStatusArray();
      if (data.hasOwnProperty('OrderStatus'))
        obj.orderStatus = ApiClient.convertToType(data['OrderStatus'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderStatus
 */
PsDomainModelOrderStatusV100OrderStatusArray.prototype.orderStatus = undefined;

