/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PsDomainModelOrderStatusV200OrderStatusDetailArray model module.
 * @module model/PsDomainModelOrderStatusV200OrderStatusDetailArray
 * @version 0.0.1
 */
export default class PsDomainModelOrderStatusV200OrderStatusDetailArray {
  /**
   * Constructs a new <code>PsDomainModelOrderStatusV200OrderStatusDetailArray</code>.
   * @alias module:model/PsDomainModelOrderStatusV200OrderStatusDetailArray
   * @class
   * @param orderStatusDetail {Object} 
   */
  constructor(orderStatusDetail) {
    this.orderStatusDetail = orderStatusDetail;
  }

  /**
   * Constructs a <code>PsDomainModelOrderStatusV200OrderStatusDetailArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsDomainModelOrderStatusV200OrderStatusDetailArray} obj Optional instance to populate.
   * @return {module:model/PsDomainModelOrderStatusV200OrderStatusDetailArray} The populated <code>PsDomainModelOrderStatusV200OrderStatusDetailArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PsDomainModelOrderStatusV200OrderStatusDetailArray();
      if (data.hasOwnProperty('OrderStatusDetail'))
        obj.orderStatusDetail = ApiClient.convertToType(data['OrderStatusDetail'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderStatusDetail
 */
PsDomainModelOrderStatusV200OrderStatusDetailArray.prototype.orderStatusDetail = undefined;

