/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class QuantityUoM.
 * @enum {Object}
 * @readonly
 */
const QuantityUoM = {
  /**
   * value: "BX"
   * @const
   */
  BX: "BX",

  /**
   * value: "CA"
   * @const
   */
  CA: "CA",

  /**
   * value: "DZ"
   * @const
   */
  DZ: "DZ",

  /**
   * value: "EA"
   * @const
   */
  EA: "EA",

  /**
   * value: "KT"
   * @const
   */
  KT: "KT",

  /**
   * value: "PR"
   * @const
   */
  PR: "PR",

  /**
   * value: "PK"
   * @const
   */
  PK: "PK",

  /**
   * value: "RL"
   * @const
   */
  RL: "RL",

  /**
   * value: "ST"
   * @const
   */
  ST: "ST",

  /**
   * value: "SL"
   * @const
   */
  SL: "SL",

  /**
   * value: "TH"
   * @const
   */
  TH: "TH",

  /**
   * Returns a <code>QuantityUoM</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/QuantityUoM} The enum <code>QuantityUoM</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {QuantityUoM};