/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RealFilterValues model module.
 * @module model/RealFilterValues
 * @version 0.0.1
 */
export default class RealFilterValues {
  /**
   * Constructs a new <code>RealFilterValues</code>.
   * @alias module:model/RealFilterValues
   * @class
   * @param labelSizeArray {Object} 
   * @param partColorArray {Object} 
   * @param selectionArray {Object} 
   */
  constructor(labelSizeArray, partColorArray, selectionArray) {
    this.labelSizeArray = labelSizeArray;
    this.partColorArray = partColorArray;
    this.selectionArray = selectionArray;
  }

  /**
   * Constructs a <code>RealFilterValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RealFilterValues} obj Optional instance to populate.
   * @return {module:model/RealFilterValues} The populated <code>RealFilterValues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RealFilterValues();
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], Object);
      if (data.hasOwnProperty('partId'))
        obj.partId = ApiClient.convertToType(data['partId'], Object);
      if (data.hasOwnProperty('LabelSizeArray'))
        obj.labelSizeArray = ApiClient.convertToType(data['LabelSizeArray'], Object);
      if (data.hasOwnProperty('PartColorArray'))
        obj.partColorArray = ApiClient.convertToType(data['PartColorArray'], Object);
      if (data.hasOwnProperty('SelectionArray'))
        obj.selectionArray = ApiClient.convertToType(data['SelectionArray'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} productId
 */
RealFilterValues.prototype.productId = undefined;

/**
 * @member {Object} partId
 */
RealFilterValues.prototype.partId = undefined;

/**
 * @member {Object} labelSizeArray
 */
RealFilterValues.prototype.labelSizeArray = undefined;

/**
 * @member {Object} partColorArray
 */
RealFilterValues.prototype.partColorArray = undefined;

/**
 * @member {Object} selectionArray
 */
RealFilterValues.prototype.selectionArray = undefined;

