/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RelatedProductArray model module.
 * @module model/RelatedProductArray
 * @version 0.0.1
 */
export default class RelatedProductArray {
  /**
   * Constructs a new <code>RelatedProductArray</code>.
   * @alias module:model/RelatedProductArray
   * @class
   * @param relatedProduct {Object} 
   */
  constructor(relatedProduct) {
    this.relatedProduct = relatedProduct;
  }

  /**
   * Constructs a <code>RelatedProductArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelatedProductArray} obj Optional instance to populate.
   * @return {module:model/RelatedProductArray} The populated <code>RelatedProductArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelatedProductArray();
      if (data.hasOwnProperty('RelatedProduct'))
        obj.relatedProduct = ApiClient.convertToType(data['RelatedProduct'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} relatedProduct
 */
RelatedProductArray.prototype.relatedProduct = undefined;

