/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SalesOrderNumber model module.
 * @module model/SalesOrderNumber
 * @version 0.0.1
 */
export default class SalesOrderNumber {
  /**
   * Constructs a new <code>SalesOrderNumber</code>.
   * Field       Description     Data Type       Required salesOrderNumber    The sales order number  64 STRING       TRUE
   * @alias module:model/SalesOrderNumber
   * @class
   * @param salesOrderNumber {Object} 
   */
  constructor(salesOrderNumber) {
    this.salesOrderNumber = salesOrderNumber;
  }

  /**
   * Constructs a <code>SalesOrderNumber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SalesOrderNumber} obj Optional instance to populate.
   * @return {module:model/SalesOrderNumber} The populated <code>SalesOrderNumber</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SalesOrderNumber();
      if (data.hasOwnProperty('salesOrderNumber'))
        obj.salesOrderNumber = ApiClient.convertToType(data['salesOrderNumber'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} salesOrderNumber
 */
SalesOrderNumber.prototype.salesOrderNumber = undefined;

