/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Severity from './Severity';

/**
 * The ServiceMessage model module.
 * @module model/ServiceMessage
 * @version 0.0.1
 */
export default class ServiceMessage {
  /**
   * Constructs a new <code>ServiceMessage</code>.
   * @alias module:model/ServiceMessage
   * @class
   * @param code {Object} 
   * @param description {Object} 
   * @param severity {module:model/Severity} 
   */
  constructor(code, description, severity) {
    this.code = code;
    this.description = description;
    this.severity = severity;
  }

  /**
   * Constructs a <code>ServiceMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceMessage} obj Optional instance to populate.
   * @return {module:model/ServiceMessage} The populated <code>ServiceMessage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceMessage();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('severity'))
        obj.severity = Severity.constructFromObject(data['severity']);
    }
    return obj;
  }
}

/**
 * @member {Object} code
 */
ServiceMessage.prototype.code = undefined;

/**
 * @member {Object} description
 */
ServiceMessage.prototype.description = undefined;

/**
 * @member {module:model/Severity} severity
 */
ServiceMessage.prototype.severity = undefined;

