/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FreightDetails from './FreightDetails';
import ShipTo from './ShipTo';

/**
 * The Shipment model module.
 * @module model/Shipment
 * @version 0.0.1
 */
export default class Shipment {
  /**
   * Constructs a new <code>Shipment</code>.
   * @alias module:model/Shipment
   * @class
   * @param shipTo {module:model/ShipTo} 
   * @param packingListRequired {Object} 
   * @param blindShip {Object} 
   * @param allowConsolidation {Object} 
   * @param freightDetails {module:model/FreightDetails} 
   * @param thirdPartyAccount {Object} 
   */
  constructor(shipTo, packingListRequired, blindShip, allowConsolidation, freightDetails, thirdPartyAccount) {
    this.shipTo = shipTo;
    this.packingListRequired = packingListRequired;
    this.blindShip = blindShip;
    this.allowConsolidation = allowConsolidation;
    this.freightDetails = freightDetails;
    this.thirdPartyAccount = thirdPartyAccount;
  }

  /**
   * Constructs a <code>Shipment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Shipment} obj Optional instance to populate.
   * @return {module:model/Shipment} The populated <code>Shipment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Shipment();
      if (data.hasOwnProperty('ShipTo'))
        obj.shipTo = ShipTo.constructFromObject(data['ShipTo']);
      if (data.hasOwnProperty('packingListRequired'))
        obj.packingListRequired = ApiClient.convertToType(data['packingListRequired'], Object);
      if (data.hasOwnProperty('blindShip'))
        obj.blindShip = ApiClient.convertToType(data['blindShip'], Object);
      if (data.hasOwnProperty('allowConsolidation'))
        obj.allowConsolidation = ApiClient.convertToType(data['allowConsolidation'], Object);
      if (data.hasOwnProperty('FreightDetails'))
        obj.freightDetails = FreightDetails.constructFromObject(data['FreightDetails']);
      if (data.hasOwnProperty('ThirdPartyAccount'))
        obj.thirdPartyAccount = ApiClient.convertToType(data['ThirdPartyAccount'], Object);
      if (data.hasOwnProperty('shipReferences'))
        obj.shipReferences = ApiClient.convertToType(data['shipReferences'], Object);
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/ShipTo} shipTo
 */
Shipment.prototype.shipTo = undefined;

/**
 * @member {Object} packingListRequired
 */
Shipment.prototype.packingListRequired = undefined;

/**
 * @member {Object} blindShip
 */
Shipment.prototype.blindShip = undefined;

/**
 * @member {Object} allowConsolidation
 */
Shipment.prototype.allowConsolidation = undefined;

/**
 * @member {module:model/FreightDetails} freightDetails
 */
Shipment.prototype.freightDetails = undefined;

/**
 * @member {Object} thirdPartyAccount
 */
Shipment.prototype.thirdPartyAccount = undefined;

/**
 * Array of `two` strings max of identifiers used as the reference fields used during the shipping process. A shipReference can be a `purchase order number`, `customer number`, `company name`, `Bill of Lading number`, or a phrase that identifies that shipment
 * @member {Object} shipReferences
 */
Shipment.prototype.shipReferences = undefined;

/**
 * @member {Object} comments
 */
Shipment.prototype.comments = undefined;

