/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ShipmentLocationArray model module.
 * @module model/ShipmentLocationArray
 * @version 0.0.1
 */
export default class ShipmentLocationArray {
  /**
   * Constructs a new <code>ShipmentLocationArray</code>.
   * @alias module:model/ShipmentLocationArray
   * @class
   * @param shipmentLocation {Object} 
   */
  constructor(shipmentLocation) {
    this.shipmentLocation = shipmentLocation;
  }

  /**
   * Constructs a <code>ShipmentLocationArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShipmentLocationArray} obj Optional instance to populate.
   * @return {module:model/ShipmentLocationArray} The populated <code>ShipmentLocationArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShipmentLocationArray();
      if (data.hasOwnProperty('ShipmentLocation'))
        obj.shipmentLocation = ApiClient.convertToType(data['ShipmentLocation'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} shipmentLocation
 */
ShipmentLocationArray.prototype.shipmentLocation = undefined;

