/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The StatusArray model module.
 * @module model/StatusArray
 * @version 0.0.1
 */
export default class StatusArray {
  /**
   * Constructs a new <code>StatusArray</code>.
   * @alias module:model/StatusArray
   * @class
   * @param status {Object} 
   */
  constructor(status) {
    this.status = status;
  }

  /**
   * Constructs a <code>StatusArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatusArray} obj Optional instance to populate.
   * @return {module:model/StatusArray} The populated <code>StatusArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StatusArray();
      if (data.hasOwnProperty('Status'))
        obj.status = ApiClient.convertToType(data['Status'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
StatusArray.prototype.status = undefined;

