/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TaxInformationArray model module.
 * @module model/TaxInformationArray
 * @version 0.0.1
 */
export default class TaxInformationArray {
  /**
   * Constructs a new <code>TaxInformationArray</code>.
   * @alias module:model/TaxInformationArray
   * @class
   * @param taxInformation {Object} 
   */
  constructor(taxInformation) {
    this.taxInformation = taxInformation;
  }

  /**
   * Constructs a <code>TaxInformationArray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaxInformationArray} obj Optional instance to populate.
   * @return {module:model/TaxInformationArray} The populated <code>TaxInformationArray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TaxInformationArray();
      if (data.hasOwnProperty('TaxInformation'))
        obj.taxInformation = ApiClient.convertToType(data['TaxInformation'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} taxInformation
 */
TaxInformationArray.prototype.taxInformation = undefined;

