/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class TaxTypeOutput.
 * @enum {Object}
 * @readonly
 */
const TaxTypeOutput = {
  /**
   * value: "SALES"
   * @const
   */
  SALES: "SALES",

  /**
   * value: "HST/GST"
   * @const
   */
  HSTGST: "HST/GST",

  /**
   * value: "PST"
   * @const
   */
  PST: "PST",

  /**
   * value: "VAT"
   * @const
   */
  VAT: "VAT",

  /**
   * Returns a <code>TaxTypeOutput</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TaxTypeOutput} The enum <code>TaxTypeOutput</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {TaxTypeOutput};