/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class TaxTypeInput.
 * @enum {Object}
 * @readonly
 */
const TaxTypeInput = {
  /**
   * value: "Hst-Gst"
   * @const
   */
  hstGst: "Hst-Gst",

  /**
   * value: "Pst"
   * @const
   */
  pst: "Pst",

  /**
   * value: "SalesTax"
   * @const
   */
  salesTax: "SalesTax",

  /**
   * Returns a <code>TaxTypeInput</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TaxTypeInput} The enum <code>TaxTypeInput</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {TaxTypeInput};