/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Typeset model module.
 * @module model/Typeset
 * @version 0.0.1
 */
export default class Typeset {
  /**
   * Constructs a new <code>Typeset</code>.
   * @alias module:model/Typeset
   * @class
   * @param sequenceNumber {Object} The order number of the typeset
   * @param value {Object} The typeset to be used on the order
   * @param font {Object} 
   * @param fontSize {Object} The font size to use for the typeset
   */
  constructor(sequenceNumber, value, font, fontSize) {
    this.sequenceNumber = sequenceNumber;
    this.value = value;
    this.font = font;
    this.fontSize = fontSize;
  }

  /**
   * Constructs a <code>Typeset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Typeset} obj Optional instance to populate.
   * @return {module:model/Typeset} The populated <code>Typeset</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Typeset();
      if (data.hasOwnProperty('sequenceNumber'))
        obj.sequenceNumber = ApiClient.convertToType(data['sequenceNumber'], Object);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
      if (data.hasOwnProperty('font'))
        obj.font = ApiClient.convertToType(data['font'], Object);
      if (data.hasOwnProperty('fontSize'))
        obj.fontSize = ApiClient.convertToType(data['fontSize'], Object);
    }
    return obj;
  }
}

/**
 * The order number of the typeset
 * @member {Object} sequenceNumber
 */
Typeset.prototype.sequenceNumber = undefined;

/**
 * The typeset to be used on the order
 * @member {Object} value
 */
Typeset.prototype.value = undefined;

/**
 * @member {Object} font
 */
Typeset.prototype.font = undefined;

/**
 * The font size to use for the typeset
 * @member {Object} fontSize
 */
Typeset.prototype.fontSize = undefined;

