/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import GetInvoiceResponse from '../model/GetInvoiceResponse';
import GetVoidedResponse from '../model/GetVoidedResponse';
import HTTPValidationError from '../model/HTTPValidationError';
import PsDomainModelInvoiceQueryType from '../model/PsDomainModelInvoiceQueryType';

/**
* Invoice service.
* @module api/InvoiceApi
* @version 0.0.1
*/
export default class InvoiceApi {

    /**
    * Constructs a new InvoiceApi. 
    * @alias module:api/InvoiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getInvoices operation.
     * @callback moduleapi/InvoiceApi~getInvoicesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetInvoiceResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Invoices
     * @param {Object} supplierCode 
     * @param {module:model/PsDomainModelInvoiceQueryType} queryType 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.body 
     * @param {Object} opts.referenceNumber 
     * @param {Object} opts.requestedDate 
     * @param {Object} opts.availableTimestamp 
     * @param {Object} opts.environment  (default to <.>)
     * @param {Object} opts.xForwardedFor 
     * @param {Object} opts.xAccountId 
     * @param {module:api/InvoiceApi~getInvoicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getInvoices(supplierCode, queryType, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'supplierCode' is set
      if (supplierCode === undefined || supplierCode === null) {
        throw new Error("Missing the required parameter 'supplierCode' when calling getInvoices");
      }
      // verify the required parameter 'queryType' is set
      if (queryType === undefined || queryType === null) {
        throw new Error("Missing the required parameter 'queryType' when calling getInvoices");
      }

      let pathParams = {
        'supplier_code': supplierCode
      };
      let queryParams = {
        'query_type': queryType,'reference_number': opts['referenceNumber'],'requested_date': opts['requestedDate'],'available_timestamp': opts['availableTimestamp'],'environment': opts['environment']
      };
      let headerParams = {
        'X-Forwarded-For': opts['xForwardedFor'],'x-account-id': opts['xAccountId']
      };
      let formParams = {
        
      };

      let authNames = ['APIKeyHeader', 'HTTPBasic', 'OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GetInvoiceResponse;

      return this.apiClient.callApi(
        '/v1.0.0/suppliers/{supplier_code}/invoices/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getVoidedInvoices operation.
     * @callback moduleapi/InvoiceApi~getVoidedInvoicesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetVoidedResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Voided Invoices
     * This endpoint is used to retrieve a list of voided invoices. When QueryType&#x3D;1(PO_NUMBER_SEARCH) or 2(INVOICE_NUMBER_SEARCH) reference_number must be filled in.
     * @param {Object} supplierCode 
     * @param {module:model/PsDomainModelInvoiceQueryType} queryType 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.body 
     * @param {Object} opts.referenceNumber 
     * @param {Object} opts.requestedDate 
     * @param {Object} opts.availableTimestamp 
     * @param {Object} opts.environment  (default to <.>)
     * @param {Object} opts.xForwardedFor 
     * @param {Object} opts.xAccountId 
     * @param {module:api/InvoiceApi~getVoidedInvoicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getVoidedInvoices(supplierCode, queryType, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'supplierCode' is set
      if (supplierCode === undefined || supplierCode === null) {
        throw new Error("Missing the required parameter 'supplierCode' when calling getVoidedInvoices");
      }
      // verify the required parameter 'queryType' is set
      if (queryType === undefined || queryType === null) {
        throw new Error("Missing the required parameter 'queryType' when calling getVoidedInvoices");
      }

      let pathParams = {
        'supplier_code': supplierCode
      };
      let queryParams = {
        'query_type': queryType,'reference_number': opts['referenceNumber'],'requested_date': opts['requestedDate'],'available_timestamp': opts['availableTimestamp'],'environment': opts['environment']
      };
      let headerParams = {
        'X-Forwarded-For': opts['xForwardedFor'],'x-account-id': opts['xAccountId']
      };
      let formParams = {
        
      };

      let authNames = ['APIKeyHeader', 'HTTPBasic', 'OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GetVoidedResponse;

      return this.apiClient.callApi(
        '/v1.0.0/suppliers/{supplier_code}/voided-invoices/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}