/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ArtworkFile', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.ArtworkFile();
      });

      it('should create an instance of ArtworkFile', function() {
        // TODO: update the code to test ArtworkFile
        expect(instance).to.be.a(PsResTfulServiceApi.ArtworkFile);
      });

      it('should have the property fileName (base name: "fileName")', function() {
        // TODO: update the code to test the property fileName
        expect(instance).to.have.property('fileName');
        // expect(instance.fileName).to.be(expectedValueLiteral);
      });

      it('should have the property fileLocation (base name: "fileLocation")', function() {
        // TODO: update the code to test the property fileLocation
        expect(instance).to.have.property('fileLocation');
        // expect(instance.fileLocation).to.be(expectedValueLiteral);
      });

      it('should have the property transportMechanism (base name: "transportMechanism")', function() {
        // TODO: update the code to test the property transportMechanism
        expect(instance).to.have.property('transportMechanism');
        // expect(instance.transportMechanism).to.be(expectedValueLiteral);
      });

      it('should have the property artworkType (base name: "artworkType")', function() {
        // TODO: update the code to test the property artworkType
        expect(instance).to.have.property('artworkType');
        // expect(instance.artworkType).to.be(expectedValueLiteral);
      });

    });
  });

}));
