/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChargeInput', function() {
      beforeEach(function() {
        instance = new psrestful.ChargeInput();
      });

      it('should create an instance of ChargeInput', function() {
        // TODO: update the code to test ChargeInput
        expect(instance).to.be.a(psrestful.ChargeInput);
      });

      it('should have the property chargeId (base name: "chargeId")', function() {
        // TODO: update the code to test the property chargeId
        expect(instance).to.have.property('chargeId');
        // expect(instance.chargeId).to.be(expectedValueLiteral);
      });

      it('should have the property chargeName (base name: "chargeName")', function() {
        // TODO: update the code to test the property chargeName
        expect(instance).to.have.property('chargeName');
        // expect(instance.chargeName).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property chargeType (base name: "chargeType")', function() {
        // TODO: update the code to test the property chargeType
        expect(instance).to.have.property('chargeType');
        // expect(instance.chargeType).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "Quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property unitPrice (base name: "unitPrice")', function() {
        // TODO: update the code to test the property unitPrice
        expect(instance).to.have.property('unitPrice');
        // expect(instance.unitPrice).to.be(expectedValueLiteral);
      });

      it('should have the property extendedPrice (base name: "extendedPrice")', function() {
        // TODO: update the code to test the property extendedPrice
        expect(instance).to.have.property('extendedPrice');
        // expect(instance.extendedPrice).to.be(expectedValueLiteral);
      });

    });
  });

}));
