/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChargePrice', function() {
      beforeEach(function() {
        instance = new psrestful.ChargePrice();
      });

      it('should create an instance of ChargePrice', function() {
        // TODO: update the code to test ChargePrice
        expect(instance).to.be.a(psrestful.ChargePrice);
      });

      it('should have the property xMinQty (base name: "xMinQty")', function() {
        // TODO: update the code to test the property xMinQty
        expect(instance).to.have.property('xMinQty');
        // expect(instance.xMinQty).to.be(expectedValueLiteral);
      });

      it('should have the property xUom (base name: "xUom")', function() {
        // TODO: update the code to test the property xUom
        expect(instance).to.have.property('xUom');
        // expect(instance.xUom).to.be(expectedValueLiteral);
      });

      it('should have the property yMinQty (base name: "yMinQty")', function() {
        // TODO: update the code to test the property yMinQty
        expect(instance).to.have.property('yMinQty');
        // expect(instance.yMinQty).to.be(expectedValueLiteral);
      });

      it('should have the property yUom (base name: "yUom")', function() {
        // TODO: update the code to test the property yUom
        expect(instance).to.have.property('yUom');
        // expect(instance.yUom).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property discountCode (base name: "discountCode")', function() {
        // TODO: update the code to test the property discountCode
        expect(instance).to.have.property('discountCode');
        // expect(instance.discountCode).to.be(expectedValueLiteral);
      });

      it('should have the property repeatPrice (base name: "repeatPrice")', function() {
        // TODO: update the code to test the property repeatPrice
        expect(instance).to.have.property('repeatPrice');
        // expect(instance.repeatPrice).to.be(expectedValueLiteral);
      });

      it('should have the property repeatDiscountCode (base name: "repeatDiscountCode")', function() {
        // TODO: update the code to test the property repeatDiscountCode
        expect(instance).to.have.property('repeatDiscountCode');
        // expect(instance.repeatDiscountCode).to.be(expectedValueLiteral);
      });

      it('should have the property priceEffectiveDate (base name: "priceEffectiveDate")', function() {
        // TODO: update the code to test the property priceEffectiveDate
        expect(instance).to.have.property('priceEffectiveDate');
        // expect(instance.priceEffectiveDate).to.be(expectedValueLiteral);
      });

      it('should have the property priceExpiryDate (base name: "priceExpiryDate")', function() {
        // TODO: update the code to test the property priceExpiryDate
        expect(instance).to.have.property('priceExpiryDate');
        // expect(instance.priceExpiryDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
