/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DecorationInput', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.DecorationInput();
      });

      it('should create an instance of DecorationInput', function() {
        // TODO: update the code to test DecorationInput
        expect(instance).to.be.a(PsResTfulServiceApi.DecorationInput);
      });

      it('should have the property decorationId (base name: "decorationId")', function() {
        // TODO: update the code to test the property decorationId
        expect(instance).to.have.property('decorationId');
        // expect(instance.decorationId).to.be(expectedValueLiteral);
      });

      it('should have the property decorationName (base name: "decorationName")', function() {
        // TODO: update the code to test the property decorationName
        expect(instance).to.have.property('decorationName');
        // expect(instance.decorationName).to.be(expectedValueLiteral);
      });

      it('should have the property artwork (base name: "Artwork")', function() {
        // TODO: update the code to test the property artwork
        expect(instance).to.have.property('artwork');
        // expect(instance.artwork).to.be(expectedValueLiteral);
      });

    });
  });

}));
