/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DecorationColors', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.DecorationColors();
      });

      it('should create an instance of DecorationColors', function() {
        // TODO: update the code to test DecorationColors
        expect(instance).to.be.a(PsResTfulServiceApi.DecorationColors);
      });

      it('should have the property productId (base name: "productId")', function() {
        // TODO: update the code to test the property productId
        expect(instance).to.have.property('productId');
        // expect(instance.productId).to.be(expectedValueLiteral);
      });

      it('should have the property locationId (base name: "locationId")', function() {
        // TODO: update the code to test the property locationId
        expect(instance).to.have.property('locationId');
        // expect(instance.locationId).to.be(expectedValueLiteral);
      });

      it('should have the property pmsMatch (base name: "pmsMatch")', function() {
        // TODO: update the code to test the property pmsMatch
        expect(instance).to.have.property('pmsMatch');
        // expect(instance.pmsMatch).to.be(expectedValueLiteral);
      });

      it('should have the property fullColor (base name: "fullColor")', function() {
        // TODO: update the code to test the property fullColor
        expect(instance).to.have.property('fullColor');
        // expect(instance.fullColor).to.be(expectedValueLiteral);
      });

      it('should have the property colorArray (base name: "ColorArray")', function() {
        // TODO: update the code to test the property colorArray
        expect(instance).to.have.property('colorArray');
        // expect(instance.colorArray).to.be(expectedValueLiteral);
      });

      it('should have the property decorationMethodArray (base name: "DecorationMethodArray")', function() {
        // TODO: update the code to test the property decorationMethodArray
        expect(instance).to.have.property('decorationMethodArray');
        // expect(instance.decorationMethodArray).to.be(expectedValueLiteral);
      });

    });
  });

}));
