/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DecorationUomType', function() {
      beforeEach(function() {
        instance = psrestful.DecorationUomType;
      });

      it('should create an instance of DecorationUomType', function() {
        // TODO: update the code to test DecorationUomType
        expect(instance).to.be.a('object');
      });

      it('should have the property colors', function() {
        expect(instance).to.have.property('colors');
        expect(instance.colors).to.be("Colors");
      });

      it('should have the property inches', function() {
        expect(instance).to.have.property('inches');
        expect(instance.inches).to.be("Inches");
      });

      it('should have the property other', function() {
        expect(instance).to.have.property('other');
        expect(instance.other).to.be("Other");
      });

      it('should have the property stitches', function() {
        expect(instance).to.have.property('stitches');
        expect(instance.stitches).to.be("Stitches");
      });

      it('should have the property squareInches', function() {
        expect(instance).to.have.property('squareInches');
        expect(instance.squareInches).to.be("SquareInches");
      });

      it('should have the property locations', function() {
        expect(instance).to.have.property('locations');
        expect(instance.locations).to.be("Locations");
      });

    });
  });

}));
