/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Dimension', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.Dimension();
      });

      it('should create an instance of Dimension', function() {
        // TODO: update the code to test Dimension
        expect(instance).to.be.a(PsResTfulServiceApi.Dimension);
      });

      it('should have the property dimensionUom (base name: "dimensionUom")', function() {
        // TODO: update the code to test the property dimensionUom
        expect(instance).to.have.property('dimensionUom');
        // expect(instance.dimensionUom).to.be(expectedValueLiteral);
      });

      it('should have the property depth (base name: "depth")', function() {
        // TODO: update the code to test the property depth
        expect(instance).to.have.property('depth');
        // expect(instance.depth).to.be(expectedValueLiteral);
      });

      it('should have the property height (base name: "height")', function() {
        // TODO: update the code to test the property height
        expect(instance).to.have.property('height');
        // expect(instance.height).to.be(expectedValueLiteral);
      });

      it('should have the property width (base name: "width")', function() {
        // TODO: update the code to test the property width
        expect(instance).to.have.property('width');
        // expect(instance.width).to.be(expectedValueLiteral);
      });

      it('should have the property weightUom (base name: "weightUom")', function() {
        // TODO: update the code to test the property weightUom
        expect(instance).to.have.property('weightUom');
        // expect(instance.weightUom).to.be(expectedValueLiteral);
      });

      it('should have the property weight (base name: "weight")', function() {
        // TODO: update the code to test the property weight
        expect(instance).to.have.property('weight');
        // expect(instance.weight).to.be(expectedValueLiteral);
      });

    });
  });

}));
