/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Fob', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.Fob();
      });

      it('should create an instance of Fob', function() {
        // TODO: update the code to test Fob
        expect(instance).to.be.a(PsResTfulServiceApi.Fob);
      });

      it('should have the property fobId (base name: "fobId")', function() {
        // TODO: update the code to test the property fobId
        expect(instance).to.have.property('fobId');
        // expect(instance.fobId).to.be(expectedValueLiteral);
      });

      it('should have the property fobPostalCode (base name: "fobPostalCode")', function() {
        // TODO: update the code to test the property fobPostalCode
        expect(instance).to.have.property('fobPostalCode');
        // expect(instance.fobPostalCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
