/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LocationInput', function() {
      beforeEach(function() {
        instance = new psrestful.LocationInput();
      });

      it('should create an instance of LocationInput', function() {
        // TODO: update the code to test LocationInput
        expect(instance).to.be.a(psrestful.LocationInput);
      });

      it('should have the property locationLinkId (base name: "locationLinkId")', function() {
        // TODO: update the code to test the property locationLinkId
        expect(instance).to.have.property('locationLinkId');
        // expect(instance.locationLinkId).to.be(expectedValueLiteral);
      });

      it('should have the property locationId (base name: "locationId")', function() {
        // TODO: update the code to test the property locationId
        expect(instance).to.have.property('locationId');
        // expect(instance.locationId).to.be(expectedValueLiteral);
      });

      it('should have the property locationName (base name: "locationName")', function() {
        // TODO: update the code to test the property locationName
        expect(instance).to.have.property('locationName');
        // expect(instance.locationName).to.be(expectedValueLiteral);
      });

      it('should have the property decorationArray (base name: "DecorationArray")', function() {
        // TODO: update the code to test the property decorationArray
        expect(instance).to.have.property('decorationArray');
        // expect(instance.decorationArray).to.be(expectedValueLiteral);
      });

    });
  });

}));
