/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProductPrice', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.ProductPrice();
      });

      it('should create an instance of ProductPrice', function() {
        // TODO: update the code to test ProductPrice
        expect(instance).to.be.a(PsResTfulServiceApi.ProductPrice);
      });

      it('should have the property quantityMax (base name: "quantityMax")', function() {
        // TODO: update the code to test the property quantityMax
        expect(instance).to.have.property('quantityMax');
        // expect(instance.quantityMax).to.be(expectedValueLiteral);
      });

      it('should have the property quantityMin (base name: "quantityMin")', function() {
        // TODO: update the code to test the property quantityMin
        expect(instance).to.have.property('quantityMin');
        // expect(instance.quantityMin).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property discountCode (base name: "discountCode")', function() {
        // TODO: update the code to test the property discountCode
        expect(instance).to.have.property('discountCode');
        // expect(instance.discountCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
