/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProductResponseV200', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.ProductResponseV200();
      });

      it('should create an instance of ProductResponseV200', function() {
        // TODO: update the code to test ProductResponseV200
        expect(instance).to.be.a(PsResTfulServiceApi.ProductResponseV200);
      });

      it('should have the property product (base name: "Product")', function() {
        // TODO: update the code to test the property product
        expect(instance).to.have.property('product');
        // expect(instance.product).to.be(expectedValueLiteral);
      });

      it('should have the property serviceMessageArray (base name: "ServiceMessageArray")', function() {
        // TODO: update the code to test the property serviceMessageArray
        expect(instance).to.have.property('serviceMessageArray');
        // expect(instance.serviceMessageArray).to.be(expectedValueLiteral);
      });

    });
  });

}));
