/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProductPackage', function() {
      beforeEach(function() {
        instance = new psrestful.ProductPackage();
      });

      it('should create an instance of ProductPackage', function() {
        // TODO: update the code to test ProductPackage
        expect(instance).to.be.a(psrestful.ProductPackage);
      });

      it('should have the property _default (base name: "default")', function() {
        // TODO: update the code to test the property _default
        expect(instance).to.have.property('_default');
        // expect(instance._default).to.be(expectedValueLiteral);
      });

      it('should have the property packageType (base name: "packageType")', function() {
        // TODO: update the code to test the property packageType
        expect(instance).to.have.property('packageType');
        // expect(instance.packageType).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property dimensionUom (base name: "dimensionUom")', function() {
        // TODO: update the code to test the property dimensionUom
        expect(instance).to.have.property('dimensionUom');
        // expect(instance.dimensionUom).to.be(expectedValueLiteral);
      });

      it('should have the property depth (base name: "depth")', function() {
        // TODO: update the code to test the property depth
        expect(instance).to.have.property('depth');
        // expect(instance.depth).to.be(expectedValueLiteral);
      });

      it('should have the property height (base name: "height")', function() {
        // TODO: update the code to test the property height
        expect(instance).to.have.property('height');
        // expect(instance.height).to.be(expectedValueLiteral);
      });

      it('should have the property width (base name: "width")', function() {
        // TODO: update the code to test the property width
        expect(instance).to.have.property('width');
        // expect(instance.width).to.be(expectedValueLiteral);
      });

      it('should have the property weightUom (base name: "weightUom")', function() {
        // TODO: update the code to test the property weightUom
        expect(instance).to.have.property('weightUom');
        // expect(instance.weightUom).to.be(expectedValueLiteral);
      });

      it('should have the property weight (base name: "weight")', function() {
        // TODO: update the code to test the property weight
        expect(instance).to.have.property('weight');
        // expect(instance.weight).to.be(expectedValueLiteral);
      });

    });
  });

}));
