/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PsDomainModelPpcFobPoint', function() {
      beforeEach(function() {
        instance = new PsResTfulServiceApi.PsDomainModelPpcFobPoint();
      });

      it('should create an instance of PsDomainModelPpcFobPoint', function() {
        // TODO: update the code to test PsDomainModelPpcFobPoint
        expect(instance).to.be.a(PsResTfulServiceApi.PsDomainModelPpcFobPoint);
      });

      it('should have the property fobId (base name: "fobId")', function() {
        // TODO: update the code to test the property fobId
        expect(instance).to.have.property('fobId');
        // expect(instance.fobId).to.be(expectedValueLiteral);
      });

      it('should have the property fobPostalCode (base name: "fobPostalCode")', function() {
        // TODO: update the code to test the property fobPostalCode
        expect(instance).to.have.property('fobPostalCode');
        // expect(instance.fobPostalCode).to.be(expectedValueLiteral);
      });

      it('should have the property fobCity (base name: "fobCity")', function() {
        // TODO: update the code to test the property fobCity
        expect(instance).to.have.property('fobCity');
        // expect(instance.fobCity).to.be(expectedValueLiteral);
      });

      it('should have the property fobState (base name: "fobState")', function() {
        // TODO: update the code to test the property fobState
        expect(instance).to.have.property('fobState');
        // expect(instance.fobState).to.be(expectedValueLiteral);
      });

      it('should have the property fobCountry (base name: "fobCountry")', function() {
        // TODO: update the code to test the property fobCountry
        expect(instance).to.have.property('fobCountry');
        // expect(instance.fobCountry).to.be(expectedValueLiteral);
      });

      it('should have the property currencySupportedArray (base name: "CurrencySupportedArray")', function() {
        // TODO: update the code to test the property currencySupportedArray
        expect(instance).to.have.property('currencySupportedArray');
        // expect(instance.currencySupportedArray).to.be(expectedValueLiteral);
      });

      it('should have the property productArray (base name: "ProductArray")', function() {
        // TODO: update the code to test the property productArray
        expect(instance).to.have.property('productArray');
        // expect(instance.productArray).to.be(expectedValueLiteral);
      });

    });
  });

}));
