/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ShipmentDestinationType', function() {
      beforeEach(function() {
        instance = PsResTfulServiceApi.ShipmentDestinationType;
      });

      it('should create an instance of ShipmentDestinationType', function() {
        // TODO: update the code to test ShipmentDestinationType
        expect(instance).to.be.a('object');
      });

      it('should have the property commercial', function() {
        expect(instance).to.have.property('commercial');
        expect(instance.commercial).to.be("Commercial");
      });

      it('should have the property residential', function() {
        expect(instance).to.have.property('residential');
        expect(instance.residential).to.be("Residential");
      });

      it('should have the property none', function() {
        expect(instance).to.have.property('none');
        expect(instance.none).to.be("None");
      });

    });
  });

}));
