/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TaxTypeOutput', function() {
      beforeEach(function() {
        instance = psrestful.TaxTypeOutput;
      });

      it('should create an instance of TaxTypeOutput', function() {
        // TODO: update the code to test TaxTypeOutput
        expect(instance).to.be.a('object');
      });

      it('should have the property SALES', function() {
        expect(instance).to.have.property('SALES');
        expect(instance.SALES).to.be("SALES");
      });

      it('should have the property HSTGST', function() {
        expect(instance).to.have.property('HSTGST');
        expect(instance.HSTGST).to.be("HST/GST");
      });

      it('should have the property PST', function() {
        expect(instance).to.have.property('PST');
        expect(instance.PST).to.be("PST");
      });

      it('should have the property VAT', function() {
        expect(instance).to.have.property('VAT');
        expect(instance.VAT).to.be("VAT");
      });

    });
  });

}));
