/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransportMechanism', function() {
      beforeEach(function() {
        instance = psrestful.TransportMechanism;
      });

      it('should create an instance of TransportMechanism', function() {
        // TODO: update the code to test TransportMechanism
        expect(instance).to.be.a('object');
      });

      it('should have the property email', function() {
        expect(instance).to.have.property('email');
        expect(instance.email).to.be("Email");
      });

      it('should have the property url', function() {
        expect(instance).to.have.property('url');
        expect(instance.url).to.be("Url");
      });

      it('should have the property ftp', function() {
        expect(instance).to.have.property('ftp');
        expect(instance.ftp).to.be("Ftp");
      });

      it('should have the property artworkToFollow', function() {
        expect(instance).to.have.property('artworkToFollow');
        expect(instance.artworkToFollow).to.be("ArtworkToFollow");
      });

    });
  });

}));
