/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.psrestful);
  }
}(this, function(expect, psrestful) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WeightUOM', function() {
      beforeEach(function() {
        instance = psrestful.WeightUOM;
      });

      it('should create an instance of WeightUOM', function() {
        // TODO: update the code to test WeightUOM
        expect(instance).to.be.a('object');
      });

      it('should have the property ounces', function() {
        expect(instance).to.have.property('ounces');
        expect(instance.ounces).to.be("Ounces");
      });

      it('should have the property pounds', function() {
        expect(instance).to.have.property('pounds');
        expect(instance.pounds).to.be("Pounds");
      });

      it('should have the property grams', function() {
        expect(instance).to.have.property('grams');
        expect(instance.grams).to.be("Grams");
      });

      it('should have the property KG', function() {
        expect(instance).to.have.property('KG');
        expect(instance.KG).to.be("KG");
      });

    });
  });

}));
