/*
 * PS RESTful Service API
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PsResTfulServiceApi);
  }
}(this, function(expect, PsResTfulServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PsResTfulServiceApi.OrderShipmentNotificationApi();
  });

  describe('(package)', function() {
    describe('OrderShipmentNotificationApi', function() {
      describe('getOrderShipmentNotificationV100', function() {
        it('should call getOrderShipmentNotificationV100 successfully', function(done) {
          // TODO: uncomment, update parameter values for getOrderShipmentNotificationV100 call and complete the assertions
          /*
          var opts = {};

          instance.getOrderShipmentNotificationV100(supplierCode, queryType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PsResTfulServiceApi.GetOrderShipmentNotificationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOrderShipmentNotificationV200', function() {
        it('should call getOrderShipmentNotificationV200 successfully', function(done) {
          // TODO: uncomment, update parameter values for getOrderShipmentNotificationV200 call and complete the assertions
          /*
          var opts = {};

          instance.getOrderShipmentNotificationV200(supplierCode, queryType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PsResTfulServiceApi.GetOrderShipmentNotificationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
